# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Example_TestHelpers_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example_TestHelpers_iOS
  pod 'ArgumentParser', :path => '../../'
  pod 'ArgumentParserToolInfo', :path => '../../'
  pod 'ArgumentParserTestHelpers', :path => '../../'

end
